### ISSUE TITLE
Christmas calendar

### ISSUE THREAD

**Issue by JesperKauppinen** [rickywid/app-ideas#2]
## Name
Christmas Calendar

## Difficulty 
Intermediate

## 📝 Project Description
An Advent calendar is a special calendar used to count the days of Advent in anticipation of Christmas. Developers desing they own calendar and implements that as web app.  Calendar that has 24 doors. Each door include content like text, video, recipe, link to a charity. Whatever you wanna include. If you dont celebrate cristmas and dont wanna do adcent calendar you can do something similar, be creative.

## 📑User Stories
- [ ] User see 24 clickable objects that each include number (1-24)
- [ ] When user clicks one of these buttons (doors), user can see content, for example text, image, video, quiz, recipe...
- [ ] Door clicks have special sound

## 🌟 Bonus features (optional)
- [ ] User can not open doors of days that are not yet past. How ever for reviewing purposes user should the content for most od doors
- [ ] Users can create their own calenders
- [ ] Users can set bg img for their calender
- [ ] Users can add images, embed videos and text to their calender content
- [ ] User can share their calender for others
- [ ] All calenders are listed by popularity, if that is implemented.
- [ ] Users can rate calenders made by others, for example upvote / downvote. This count will be shown in the list of calenders.

## Useful links and resources
- [wikipedia](https://en.wikipedia.org/wiki/Advent_calendar)

## Example projects
- [Example](https://calendar.myadvent.net/?id=6660d6a578f3c2afecaeb07ad5cdf43b)
- [another example](https://www.adventcalendar.com/demo/)

**Comment by rickywid** [comment]
Looks good!

You have a few spelling errors in your description. You wrote 'adcent' instead of advent and 'desing' instead of design. But other than that everything else looks good.

**Comment by rickywid** [comment]
Also could you mark your project ideas with the `new idea` label. You can assign your task with a label on the right side of the page under Labels.
