### ISSUE TITLE
Blog

### ISSUE THREAD

**Issue by JesperKauppinen** [rickywid/app-ideas#3]
## Name
Blog

## Difficulty 
Beginner

## 📝 Project Description
User can write text and publish it for other users to read. 
## 📑User Stories
- [ ] User can read one blog.
- [ ] User can like blog post, at this point likes can be saved locally
- [ ] User can remove like, at this point likes can be saved locally
- [ ] User can see total likes of blog post, at this poin 0 or 1, if they are saved locally
- [ ] User see comment field under the blog post
- [ ] User can write comments, at this point comments can be saved locally
- [ ] User see comments that they have written and send

## 🌟 Bonus features (optional)
- [ ] User can create account
- [ ] User likes on blog post are saved on server and are shown for other users.
- [ ] User comments on blog post are saved on server and are shown for other users.
- [ ] User can follow block writer.
- [ ] Users can like like or dislike comments. Total amount of likes is saved on server and is shown for all users.
- [ ] Users can write their own blog.
- [ ] All blogs are listed.
- [ ] All blogs by writers that user follow are be listed.
- [ ] All blogs of the writer are be listed
- [ ] User can sort all blog post by time, both newest to oldest and oldest to newest.
- [ ] User can sort all blog post by popularity, both most to least and least to most
- [ ] User can sort all blog post by authors name in alphapethical order both ways
- [ ] After publishing blog post, author can edit it.
- [ ] If author has edited their block post, it are shown, for example at the bottom "last edited at 10.30pm"
- [ ] User can stylish the blog post with for example marksman or html. 

## Useful links and resources
- [Wikipedia](https://en.wikipedia.org/wiki/Blog)
- [django](https://djangocentral.com/building-a-blog-application-with-django/) tutorial
- [react](https://dev.to/kingdavid/learn-react-hook-by-building-a-simple-blog-app-22i2) tutorial

## Example projects
- [nodejs](https://github.com/cosmicjs/simple-blog) github repo

**Comment by rickywid** [comment]
Approved! Next time please assign your project ideas with the `new idea` label. :+1:
